# Generated by Django 5.2.8 on 2025-11-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(auto_now_add=True, default='2025-11-20'),
            preserve_default=False,
        ),
    ]
