# Generated by Django 5.2.8 on 2025-11-21 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('bca', 'BCA'), ('computer science', 'COMPUTER SCIENCE'), ('data science', 'DATA SCIENCE'), ('cyber sequrity', 'CYBER SEQURITY'), ('ai', 'AI'), ('btech', 'BTECH'), ('bcom', 'BCOM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z ]+$', 'Only letters allowed')]),
        ),
    ]
