# Generated by Django 5.2.8 on 2025-11-24 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('english', 'English')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('bca', 'BCA'), ('computer science', 'COMPUTER SCIENCE'), ('data science', 'DATA SCIENCE'), ('cyber security', 'CYBER SECURITY'), ('ai', 'AI'), ('btech', 'BTECH'), ('bcom', 'BCOM')], max_length=100),
        ),
    ]
